language: php
php:
    - '7.0'
jdk:
- oraclejdk8


branches:
  only:
  - master

addons:
  sonarcloud:
    organization: "icarodgl-github"
    token:
      secure: "3827c0b8f119c6fa054354cff32f681402ef0d09"
script:
  - sonar-scanner

