language: php
  php:
    - '7.0'
    - hhvm # on Trusty only
  jdk:
    - oraclejdk8

branches:
  only:
  - master

addons:
  sonarcloud:
    organization: icarodgl
    token:
secure: "$sonarcloud"

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - sudo apt install php7.0-pgsql php7.0-cgi

script:
  - php -S localhost:8080
  - sonar-scanner